spring.application.name=auth-service
server.port=8081
jwt.secret=ThisIsAVeryStrongSecretKeyThatIsAtLeast32CharactersLong123!
jwt.expiration=3600000
jwt.refresh-expiration=7200000

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://postgres-server1.postgres.database.azure.com:5432/HireFlow?sslmode=require
spring.datasource.username=dushxn
spring.datasource.password=Td@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# To run without database temporarily, uncomment this line:
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=true
