sonar.projectKey=UdulaThathsaridu5624_HireFlow
sonar.organization=udulathathsaridu5624

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Exclude compiled output and generated code from general analysis
sonar.exclusions=*/target/*

# Exclude configurations, entities, DTOs, and the main application class from test coverage
# (Since these are mostly getters/setters/annotations and don't need dedicated tests)
sonar.coverage.exclusions=*/config/,/dto/,/entity/,*/*Application.java